### ISSUE TITLE
Opening index.html over file:// won't work.

### ISSUE THREAD

**Issue by Vera1128** [JayZangwill/vue-multipage#1]
dist文件夹的文件应该是需要可以在file://或者cdn上直接访问，不知道是否支持这种呢，我看了下，预估计是要将绝对路径改成相对路径，但是因为我不熟悉配置，所以留个issues，看看是否有人有解决方法:-D

**Comment by JayZangwill** [comment]
我已经把配置修改了，你git pull一下

**Comment by asxw00** [comment]
html模板引入static文件夹里的静态css文件，提示找不到该文件
http://127.0.0.1:8020/webapp1.3/dist/module/static/css/animate.css net::ERR_ABORTED这个怎么解决，这个路径里dist/module是怎么配置的？
