### ISSUE TITLE
html模板引入static文件夹里的静态css文件问题

### ISSUE THREAD

**Issue by asxw00** [JayZangwill/vue-multipage#2]
html模板引入static文件夹里的静态css文件，提示找不到该文件
 http://127.0.0.1:8020/webapp1.3/dist/module/static/css/animate.css   net::ERR_ABORTED这个怎么解决，这个路径里dist/module是怎么配置的？

**Comment by asxw00** [comment]
html模板引入static文件夹里的静态css文件，提示找不到该文件
http://127.0.0.1:8020/webapp1.3/dist/module/static/css/animate.css net::ERR_ABORTED这个怎么解决，这个路径里dist/module是怎么配置的？

**Comment by JayZangwill** [comment]
@asxw00 
您好，这个问题解决了吗？我这里没复线这个问题
